---
title: "Practica7AD"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(factoextra)
library(cluster)
```

```{r}
comercio = read_csv("data_comercio.csv", show_col_types = FALSE)
rownames(comercio) = comercio$cliente_id

datos = comercio %>% select(importe_gastado, num_articulos) %>% scale()

fviz_nbclust(x = datos, FUNcluster = kmeans, method = "wss",
             diss = dist(datos, method = "euclidean")) +
  geom_vline(xintercept = 4, linetype = 2)


set.seed(2024)
kmeans_clusters <- kmeans(x = datos, centers = 4, iter.max = 100, nstart = 100, algorithm = "Lloyd")
kmeans_clusters

fviz_cluster(object = kmeans_clusters, data = datos, show.clust.cent = TRUE,
             ellipse.type = "euclid", star.plot = TRUE, repel = TRUE) +
  theme_bw() + theme(legend.position = "none")
```

```{r}
fviz_nbclust(x = datos, FUNcluster = pam, method = "wss",
             diss = dist(datos, method = "euclid")) +
  geom_vline(xintercept = 4, linetype = 2)

kmedoids_clusters <- pam(x = datos, k = 4, metric = "euclid")
kmedoids_clusters

fviz_cluster(object = kmedoids_clusters, data = datos,
             ellipse.type = "euclid", repel = TRUE) +
  theme_bw() + theme(legend.position = "none")
```
